export const shoppingList: [string, ...string[]] = [
	'Elektrik faturası',
	'Su faturası',
	'Doğalgaz faturası',
	'İnternet faturası',
	'Digitürk ücreti',
	'Sabit telefon',
	'Kira',
	'Personel maaşları',
	'Muhasebe ücreti',
	'Dondurulmuş patates',
	'Dondurulmuş soğan halkası',
	'Dondurulmuş nugget',
	'Dondurulmuş pastalar',
	'Yaş pastalar',
	'Pasta süsleri',
	'Tost ekmeği',
	'Hamburger ekmeği',
	'Sebzeler',
	'Limon',
	'Ekmek',
	'Çikolata',
	'Kek',
	'Salça',
	'Yumurta',
	'Bardaklar',
	'Siyah çay',
	'Bitki çayları',
	'Ada çayı',
	'Toz çaylar',
	'Salep',
	'Sıcak çikolata',
	'Soğuk kahve',
	'Nescafe gold',
	'Nescafe çeşitleri',
	'Türk kahvesi',
	'Filtre kahve',
	'Yaş yufka',
	'Kaşar',
	'Beyaz peynir',
	'Çedar peyniri',
	'Sucuk',
	'Ketçap',
	'Mayonez',
	'Kola',
	'Fanta',
	'Freşa',
	'Soda',
	'Su',
	'Limonata',
	'Limonata aroması',
	'Yoğurt',
	'Ayran',
	'Turşu',
	'Cin biber',
	'Toz şeker',
	'Küp şeker',
	'Et',
	'Tavuk',
	'Ciğer',
	'Pirinç',
	'Tereyağı',
	'Sana yağ',
	'Sıvı yağ',
	'Kolonya',
	'Yüzey temizleyici',
	'Camsil',
	'Masa temizleme spreyi',
	'Bezler',
	'Çamaşır suyu',
	'Oda kokusu',
	'Z havlu',
	'Tuvalet kağıdı',
	'Havlu peçete',
	'Servis peçetesi',
	'Servis kağıdı',
	'Motor yakıtı',
	'Diğer harcamalar'
];

const items: { label: string; value: string }[] = [];

for (const item of shoppingList) {
	items.push({ label: item, value: item });
}

export default items;
